datasource:
  dbType: mysql
  driverClassName: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/dmz?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
  username: root
  password: zvan_2019